# Configuration for chart-testing
chart-dirs:
  - helm-chart

chart-repos:
  - elastic=https://helm.elastic.co
  - opensearch=https://opensearch-project.github.io/helm-charts/

helm-extra-args: --timeout 10m

validate-maintainers: false