version: 2
updates:
  # Check GitHub Actions for updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"
    groups:
      github-actions-updates:
        patterns:
          - "*"

  # Check Python dependencies in workflows
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  # Check Python dependencies in Elasticsearch module
  - package-ecosystem: "pip"
    directory: "/stac_fastapi/elasticsearch"
    schedule:
      interval: "weekly"

  # Check Python dependencies in Core module
  - package-ecosystem: "pip"
    directory: "/stac_fastapi/core"
    schedule:
      interval: "weekly"

  # Check Python dependencies in OpenSearch module
  - package-ecosystem: "pip"
    directory: "/stac_fastapi/opensearch"
    schedule:
      interval: "weekly"