version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: stac-fastapi-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - stac-network

volumes:
  redis_data:

networks:
  stac-network:
    driver: bridge