[project]
name = "stac-fastapi"
version = "6.19.0"
description = "Python library for building a STAC-compliant FastAPI application for Opensearch and Elasticsearch."
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "stac-fastapi-core",
    "stac-fastapi-elasticsearch",
    "stac-fastapi-opensearch",
    "sfeos-helpers",
]

[dependency-groups]
dev = [
    "pytest>=8,<10",
    "pytest-cov>=4.0,<7.2",
    "pytest-asyncio>=0.21,<1.5",
    "pre-commit>=3.0,<4.7",
    "ciso8601~=2.3.0",
    "httpx>=0.24.0,<0.29.0",
    "redis>=6.4,<8.1",
    "retry~=0.9.2",
    "stac-fastapi-core[sentry,redis,catalogs,validator]",
]
[tool.uv]
package = false

[tool.uv.sources]
stac-fastapi-core = { workspace = true }
stac-fastapi-elasticsearch = { workspace = true }
stac-fastapi-opensearch = { workspace = true }
sfeos_helpers = { workspace = true }

[tool.uv.workspace]
members = [
  "stac_fastapi/core*",
  "stac_fastapi/elasticsearch*",
  "stac_fastapi/opensearch*",
  "stac_fastapi/sfeos_helpers*",
]
