{{- if and (eq .Values.backend "opensearch") (.Values.opensearchSecurity.generateAdminPassword | default false) }}
{{- include "stac-fastapi.configureOpensearchSecurity" . -}}
{{- $secretName := include "stac-fastapi.opensearchAdminSecretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $usernameKey := default "username" .Values.opensearchSecurity.usernameKey -}}
{{- $passwordKey := default "password" .Values.opensearchSecurity.passwordKey -}}
{{- $username := default "admin" .Values.opensearchSecurity.username -}}
{{- $passwordLength := int (default 32 .Values.opensearchSecurity.passwordLength) -}}
{{- $passwordB64 := "" -}}
{{- if and $existing (hasKey $existing.data $passwordKey) }}
  {{- $passwordB64 = index $existing.data $passwordKey -}}
{{- else }}
  {{- $passwordB64 = randAlphaNum $passwordLength | b64enc -}}
{{- end }}
{{- $usernameB64 := b64enc $username -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "stac-fastapi.labels" . | nindent 4 }}
  {{- with .Values.opensearchSecurity.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ $usernameKey }}: {{ $usernameB64 }}
  {{ $passwordKey }}: {{ $passwordB64 }}
{{- end }}