{{- if .Values.podDisruptionBudget.enabled }}
{{- $pdbApiVersion := (include "stac-fastapi.pdb.apiVersion" . | trim) }}
apiVersion: {{ $pdbApiVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "stac-fastapi.fullname" . }}
  labels:
    {{- include "stac-fastapi.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stac-fastapi.selectorLabels" . | nindent 6 }}
{{- end }}