FROM python:3.11-slim

# build-essential is required to build a wheel for ciso8601
RUN apt update && apt install -y build-essential

RUN python -m pip install --upgrade pip
RUN python -m pip install mkdocs mkdocs-material pdocs

COPY . /opt/src

WORKDIR /opt/src

RUN python -m pip install \
    stac_fastapi/core \
    stac_fastapi/sfeos_helpers \
    stac_fastapi/elasticsearch \
    stac_fastapi/opensearch

CMD ["pdocs", \
    "as_markdown", \
    "--output_dir", \
    "docs/src/api/", \
    "--exclude_source", \
    "--overwrite", \
    "stac_fastapi"]