# Minimal storage values for STAC FastAPI 
# This configuration uses minimal storage requirements for development clusters
# It will still create PVCs but with very small storage requests

# Set backend to elasticsearch by default
backend: elasticsearch

# STAC FastAPI application configuration  
app:
  replicaCount: 1
  
  image:
    repository: ghcr.io/stac-utils/stac-fastapi
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  ingress:
    enabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  autoscaling:
    enabled: false

  env:
    STAC_FASTAPI_TITLE: "Test STAC API (Minimal Storage)"
    STAC_FASTAPI_DESCRIPTION: "STAC API for testing with minimal storage"
    ENVIRONMENT: "test"
    WEB_CONCURRENCY: "2"
    RELOAD: "true"
    DATABASE_REFRESH: "true"
    ENABLE_TRANSACTIONS_EXTENSIONS: "true"
    ENABLE_DIRECT_RESPONSE: "false"
    STAC_FASTAPI_RATE_LIMIT: "1000/minute"

# Elasticsearch with minimal storage requirements
elasticsearch:
  enabled: true
  
  clusterName: "stac-elasticsearch-test"
  replicas: 1
  # IMPORTANT: Set minimumMasterNodes to 0 for single-node with discovery.type: single-node
  minimumMasterNodes: 0
  
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  
  esJavaOpts: "-Xmx512m -Xms512m"
  
  esConfig:
    elasticsearch.yml: |
      cluster.name: "stac-elasticsearch-test"
      network.host: 0.0.0.0
      discovery.type: single-node
      action.destructive_requires_name: false
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false
      cluster.routing.allocation.disk.threshold_enabled: false
      indices.memory.index_buffer_size: 10%
      path.data: /usr/share/elasticsearch/data
  
  # MINIMAL STORAGE - This will create small PVCs
  # Most development clusters should be able to handle 1Gi PVCs
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
    # Use default storage class (remove storageClassName line to use default)
    # storageClassName: ""

opensearch:
  enabled: false

externalDatabase:
  enabled: false

monitoring:
  enabled: false

podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false