# Example values for using external Elasticsearch/OpenSearch
# Use this when you have an existing database cluster

# Choose your backend
backend: elasticsearch  # or opensearch

# STAC FastAPI application configuration
app:
  replicaCount: 3
  
  image:
    repository: ghcr.io/stac-utils/stac-fastapi
    tag: "latest"
    pullPolicy: IfNotPresent

  # Resource configuration
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  # Environment variables
  env:
    STAC_FASTAPI_TITLE: "STAC API with External Database"
    STAC_FASTAPI_DESCRIPTION: "STAC API connected to external Elasticsearch/OpenSearch cluster"
    ENVIRONMENT: "production"
    WEB_CONCURRENCY: "4"

# Disable bundled databases
elasticsearch:
  enabled: false

opensearch:
  enabled: false

# External database configuration
externalDatabase:
  enabled: true
  host: "elasticsearch.database.svc.cluster.local"  # Your external database host
  port: 9200
  ssl: true
  verifyCerts: true
  timeout: 30
  # Reference to secret containing API key
  apiKeySecret: "elasticsearch-api-key"
  apiKeySecretKey: "api-key"

# Create a secret for the API key (example)
# kubectl create secret generic elasticsearch-api-key --from-literal=api-key="your-api-key-here"